version: "3.4"
services:
  messaging-app:
    image: node:alpine
    container_name: messaging-app
    entrypoint: /bin/sh
    ports:
      - 3000:3000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true